name: maihamabat
description: batch operation for maihama.
version: 0.0.3
homepage: https://github.com/yuzumone/maihamabat

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.2
  http: ^0.12.0+4
  html: ^0.14.0+3
  puppeteer: ^1.15.1
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
